version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.12.0
jobs:
  tests:
    machine: true
    steps:
      - checkout
      - run: docker build -t salus-local .
      - run: docker build -f Dockerfile.tests -t salus-tests .
      - run: docker run salus-tests
      - run: bin/integration_test
  salus:
    docker:
      - image: gcr.io/pendo-security/salus:latest
        auth:
          username: _json_key
          password: $GCR_JSON_KEY_FILE
    steps:
      - checkout
      - attach_workspace:
          at: ~/pendo-io/pendo-appengine
      - gcp-gcr/gcr-auth
      - run: docker run -t -v $(pwd):/home/repo gcr.io/pendo-security/salus:latest
  rubocop:
    docker:
      - image: ruby:2.7.2@sha256:0fee695f3bf397bb521d8ced9e30963835fac44bc27f46393a5b91941c8a40aa
    steps:
      - checkout
      - run: apt-get update && apt-get install cmake -y
      - run: gem install bundler -v'2.0.2'
      - run: bundle install
      - run: bundle exec rubocop
workflows:
  version: 2.1
  build:
    jobs:
      - tests
      - rubocop
      - salus
